version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - nakedret
    - gocritic

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
    settings:
      hugeParam:
        sizeThreshold: 512
    disabled-checks:
      - ifElseChain
      - exitAfterDefer
      - paramTypeCombine
      - unnamedResult
      - sprintfQuotedString
      - emptyStringTest

formatters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/bpg/swimstats

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gocritic
  max-issues-per-linter: 0
  max-same-issues: 0
